/* Generated By:JavaCC: Do not edit this line. GramaticaParserConstants.java */
package dds.tp.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE = 1;
  /** RegularExpression Id. */
  int CUENTA = 2;
  /** RegularExpression Id. */
  int MAS = 3;
  /** RegularExpression Id. */
  int MENOS = 4;
  /** RegularExpression Id. */
  int POR = 5;
  /** RegularExpression Id. */
  int DIV = 6;
  /** RegularExpression Id. */
  int OPERADOR = 7;
  /** RegularExpression Id. */
  int ESPACIO = 8;
  /** RegularExpression Id. */
  int NUMERO = 9;
  /** RegularExpression Id. */
  int INDICADOR = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NOMBRE>",
    "<CUENTA>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<OPERADOR>",
    "\" \"",
    "<NUMERO>",
    "<INDICADOR>",
  };

}
