/* Generated By:JavaCC: Do not edit this line. GramaticaParserConstants.java */
package dds.tp.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CUENTA = 2;
  /** RegularExpression Id. */
  int INDICADOR = 3;
  /** RegularExpression Id. */
  int MAS = 4;
  /** RegularExpression Id. */
  int MENOS = 5;
  /** RegularExpression Id. */
  int POR = 6;
  /** RegularExpression Id. */
  int DIV = 7;
  /** RegularExpression Id. */
  int NUMERO = 8;
  /** RegularExpression Id. */
  int NOMBRE = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<CUENTA>",
    "<INDICADOR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUMERO>",
    "<NOMBRE>",
  };

}
